# Start Mongo, MySQL and Postgres databases
# Though other databases will be supported, these are the initial targets.
# Uses Docker Compose v2 as v3 doesn't support extends
version: '2'

services:

  mongo:
    extends:
      file: mongo.yml
      service: mongo

  mysql:
    extends:
      file: mysql.yml
      service: mysql

  postgres:
    extends:
      file: postgres.yml
      service: postgres
     
  mssql:
    extends:
      file: mssql.yml
      service: mssql