version: '2'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: nextauth
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: nextauth
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - "3306:3306"